name: Test

on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check Format
      run: |
        if [[ $(gofmt -l .) ]]; then
          echo " The following files are not formatted properly (run `go fmt` to resolve this issue):"
          echo "$(gofmt -l .)"
          exit 1
        else
          exit 0
        fi
      
    - name: Run Tests
      run:  go test ./...
